/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Column definition for Table */
export interface TableColumn {
  header: string
  width: number
  align?: string
}
/** Represents a shaped glyph with position and advance information */
export interface ShapedGlyph {
  glyphId: number
  xAdvance: number
  yAdvance: number
  xOffset: number
  yOffset: number
}
/** Represents a loaded font with parsing and shaping capabilities */
export declare class Font {
  /** Load a font from a file path */
  static fromFile(path: string, name: string): Font
  /** Load a font from bytes (e.g., embedded font data) */
  static fromBytes(data: Array<number>, name: string): Font
  /** Measure text width using shaping */
  measureText(text: string, size: number): number
  /** Shape text and return glyph IDs with positions */
  shapeText(text: string, size: number): Array<ShapedGlyph>
}
/** Represents a loaded image (JPEG or PNG) */
export declare class Image {
  /** Load an image from a file path */
  static fromFile(path: string): Image
}
/** Data Table with headers and rows */
export declare class Table {
  constructor(columns: Array<TableColumn>)
  addRow(row: Array<string>): void
}
/** Represents a single page in a PDF document */
export declare class Page {
  /** Create a new page with specified dimensions */
  constructor(width: number, height: number)
  /** Add text to the page at specified position with given font size */
  text(text: string, x: number, y: number, size: number): this
  /**
   * Add text to the page using a custom font (font_index + 2 for /F2, /F3, etc.)
   * /F1 is reserved for built-in Helvetica
   * Requires font reference to track glyph usage for subsetting
   */
  textWithFont(text: string, x: number, y: number, size: number, fontIndex: number, font: Font): this
  /** Add multiline text with wrapping */
  textMultiline(text: string, x: number, y: number, width: number, size: number, fontIndex: number, font: Font): this
  /**
   * Draw an image on the page
   * image_index is the index returned by document.addImage()
   */
  drawImage(imageIndex: number, x: number, y: number, width: number, height: number): this
  /** Draw a line */
  drawLine(x1: number, y1: number, x2: number, y2: number, width: number): this
  /** Draw a table */
  drawTable(table: Table, x: number, y: number, font: Font): number
}
/** Represents a PDF document with multiple pages */
export declare class Document {
  /** Create a new empty document in buffered mode */
  constructor()
  /**
   * Create a new document in streaming mode
   * Pages are written immediately as they're added
   */
  static streaming(path: string): Document
  /**
   * Register a custom font with the document
   * Returns the font index to use in page rendering
   */
  addFont(font: Font): number
  /**
   * Register an image with the document
   * Returns the image index to use in page rendering
   */
  addImage(image: Image): number
  /** Add a page to the document */
  addPage(page: Page): void
  /** Finalize a streaming document */
  finalize(): void
  /** Write the document to a file (buffered mode) */
  writeTo(path: string): void
}
