const { Document, Page, Font } = require('./index.js');
const fs = require('fs');

async function runTest() {
  try {
    console.log('Testing PDFX v1.1 Refactored Bindings...');

    // 1. Basic Buffered Test
    console.log('--- Buffered Mode Test ---');
    const doc = new Document();
    const page = new Page(595.0, 842.0);
    page.text("Hello from JavaScript (Buffered)!", 100.0, 700.0, 24.0);
    doc.addPage(page);
    doc.writeTo('test_buffered.pdf');
    console.log('Buffered PDF written to test_buffered.pdf');

    // 2. Stress Test (1000 Pages) - Streaming
    console.log('\n--- Streaming Mode Stress Test (1000 Pages) ---');
    const startTime = Date.now();
    
    // Note: Streaming constructor is a factory method
    const streamDoc = Document.streaming('test_streaming_1000.pdf');
    
    for (let i = 0; i < 1000; i++) {
        const p = new Page(595.0, 842.0);
        p.text(`Page ${i + 1}`, 50, 800, 12);
        p.text(`This is a stress test page generated by PDFX.`, 50, 780, 10);
        streamDoc.addPage(p);
        
        if ((i + 1) % 100 === 0) {
            process.stdout.write(`Generated ${i + 1} pages...\r`);
        }
    }
    console.log('\nFinalizing streaming document...');
    streamDoc.finalize();
    
    const duration = (Date.now() - startTime) / 1000;
    console.log(`\nSUCCESS: Generated 1000 pages in ${duration.toFixed(2)} seconds.`);
    
    // Check file size
    const stats = fs.statSync('test_streaming_1000.pdf');
    console.log(`Output file size: ${(stats.size / 1024 / 1024).toFixed(2)} MB`);

    // Auto-open PDF (Windows)
    console.log('Opening generated PDF...');
    require('child_process').exec('start test_streaming_1000.pdf');

  } catch (e) {
    console.error('FAILED:', e);
    process.exit(1);
  }
}

runTest();
